package com.example.ticket.common;

public enum ErrorCode {
    AUTH_REQUIRED,
    USER_BLOCKED,
    EVENT_NOT_ON_SALE,
    SEAT_NOT_AVAILABLE,
    HOLD_LIMIT_EXCEEDED,
    HOLD_EXPIRED,
    PAYMENT_DECLINED,
    PAYMENT_TIMEOUT,
    IDEMPOTENCY_CONFLICT,
    INVALID_SEAT_SET,
    HOLD_TOKEN_NOT_FOUND,
    AMOUNT_MISMATCH,
    INTERNAL_ERROR
}
